In [1]:
!pip install numpy pandas-profiling matplotlib seaborn --quiet
!pip install jovian opendatasets xgboost graphviz lightgbm scikit-learn xgboost lightgbm --upgrade --quiet
import os
import opendatasets as od
import pandas as pd
od.download('https://www.kaggle.com/datasets/siddharthmandgi/tripadvisor-restaurant-recommendation-data-usa')

WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\91981\anaconda3\lib\site-packages)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: hemaksh
Your Kaggle Key: ········
Downloading tripadvisor-restaurant-recommendation-data-usa.zip to .\tripadvisor-restaurant-recommendation-data-usa

100%|██████████| 456k/456k [00:01<00:00, 314kB/s]

In [2]:
data_dir="./tripadvisor-restaurant-recommendation-data-usa"
os.listdir(data_dir)

['TripAdvisor_RestauarantRecommendation.csv']

In [3]:
raw_data=pd.read_csv(data_dir+'/TripAdvisor_RestauarantRecommendation.csv')
raw_data

,Name,Street Address,Location,Type,Reviews,No of Reviews,Comments,Contact Number,Trip_advisor Url,Menu,Price_Range
0,Betty Lou's Seafood and Grill,318 Columbus Ave,"San Francisco, CA 94133-3908","Seafood, Vegetarian Friendly, Vegan Options",4.5 of 5 bubbles,243 reviews,NaN,+1 415-757-0569,https://www.tripadvisor.com//Restaurant_Review...,Check The Website for a Menu,$$ - $$$
1,Coach House Diner,55 State Rt 4,"Hackensack, NJ 07601-6337","Diner, American, Vegetarian Friendly",4 of 5 bubbles,84 reviews,"Both times we were there very late, after 11 P...",+1 201-488-4999,https://www.tripadvisor.com//Restaurant_Review...,Check The Website for a Menu,$$ - $$$
2,Table Talk Diner,2521 South Rd Ste C,"Poughkeepsie, NY 12601-5476","American, Diner, Vegetarian Friendly",4 of 5 bubbles,256 reviews,Waitress was very friendly but a little pricey...,+1 845-849-2839,https://www.tripadvisor.com//Restaurant_Review...,http://tabletalkdiner.com/menu/breakfast/,$$ - $$$
3,Sixty Vines,3701 Dallas Pkwy,"Plano, TX 75093-7777","American, Wine Bar, Vegetarian Friendly",4.5 of 5 bubbles,235 reviews,Not sure why I went there for the second time....,+1 469-620-8463,https://www.tripadvisor.com//Restaurant_Review...,https://sixtyvines.com/menu/plano-tx/,$$ - $$$
4,The Clam Bar,3914 Brewerton Rd,"Syracuse, NY 13212","American, Bar, Seafood",4 of 5 bubbles,285 reviews,Doesn't look like much from the outside but wa...,+1 315-458-1662,https://www.tripadvisor.com//Restaurant_Review...,Check The Website for a Menu,$$ - $$$
...,...,...,...,...,...,...,...,...,...,...,...
3057,Indigo Kitchen & Ale House,2902 164th St SW,"Lynnwood, WA 98087-3201","American, Bar, Vegetarian Friendly",4.5 of 5 bubbles,198 reviews,We had to wait a few minutes to get it but it ...,+1 425-741-8770,https://www.tripadvisor.com//Restaurant_Review...,Check The Website for a Menu,$$ - $$$
3058,City Vineyard,233 West Street,"New York City, NY 10013","American, Bar, Seafood",4.5 of 5 bubbles,374 reviews,"Came here to see Andrea Gibson perform, we wer...",+1 646-677-8350,https://www.tripadvisor.com//Restaurant_Review...,Check The Website for a Menu,$$ - $$$
3059,BRIO Tuscan Grille,3710 US Highway 9,"Freehold, NJ 07728-4801","Steakhouse, Italian, Bar",4 of 5 bubbles,211 reviews,We come to Brio once a month. They are good fo...,+1 732-683-1045,https://www.tripadvisor.com//Restaurant_Review...,http://www.brioitalian.com/menus.html,$$ - $$$
3060,Maywood Pancake house,92 W Pleasant Ave,"Maywood, NJ 07607-1336","American, Vegan Options, Gluten Free Options",4 of 5 bubbles,87 reviews,Stopped in yesterday for Breakfast. When in Je...,+1 201-880-7842,https://www.tripadvisor.com//Restaurant_Review...,http://www.maywoodpancakehouse.com/menu.html,$$ - $$$
3061,Porto Leggero,Harborside Financial Center - Plaza 5,"Jersey City, NJ 07311","Italian, Vegetarian Friendly, Vegan Options",4.5 of 5 bubbles,183 reviews,First time for dinner. 2 couples. Delicious mu...,+1 201-434-3200,https://www.tripadvisor.com//Restaurant_Review...,Check The Website for a Menu,$$$$

In [5]:
raw_data.columns

Index(['Name', 'Street Address', 'Location', 'Type', 'Reviews',
       'No of Reviews', 'Comments', 'Contact Number', 'Trip_advisor Url',
       'Menu', 'Price_Range'],
      dtype='object')

In [88]:
df=raw_data[['Name', 'Street Address', 'Location', 'Type', 'Reviews',
       'No of Reviews', 'Comments']]
df

,Name,Street Address,Location,Type,Reviews,No of Reviews,Comments
0,Betty Lou's Seafood and Grill,318 Columbus Ave,"San Francisco, CA 94133-3908","Seafood, Vegetarian Friendly, Vegan Options",4.5 of 5 bubbles,243 reviews,NaN
1,Coach House Diner,55 State Rt 4,"Hackensack, NJ 07601-6337","Diner, American, Vegetarian Friendly",4 of 5 bubbles,84 reviews,"Both times we were there very late, after 11 P..."
2,Table Talk Diner,2521 South Rd Ste C,"Poughkeepsie, NY 12601-5476","American, Diner, Vegetarian Friendly",4 of 5 bubbles,256 reviews,Waitress was very friendly but a little pricey...
3,Sixty Vines,3701 Dallas Pkwy,"Plano, TX 75093-7777","American, Wine Bar, Vegetarian Friendly",4.5 of 5 bubbles,235 reviews,Not sure why I went there for the second time....
4,The Clam Bar,3914 Brewerton Rd,"Syracuse, NY 13212","American, Bar, Seafood",4 of 5 bubbles,285 reviews,Doesn't look like much from the outside but wa...
...,...,...,...,...,...,...,...
3057,Indigo Kitchen & Ale House,2902 164th St SW,"Lynnwood, WA 98087-3201","American, Bar, Vegetarian Friendly",4.5 of 5 bubbles,198 reviews,We had to wait a few minutes to get it but it ...
3058,City Vineyard,233 West Street,"New York City, NY 10013","American, Bar, Seafood",4.5 of 5 bubbles,374 reviews,"Came here to see Andrea Gibson perform, we wer..."
3059,BRIO Tuscan Grille,3710 US Highway 9,"Freehold, NJ 07728-4801","Steakhouse, Italian, Bar",4 of 5 bubbles,211 reviews,We come to Brio once a month. They are good fo...
3060,Maywood Pancake house,92 W Pleasant Ave,"Maywood, NJ 07607-1336","American, Vegan Options, Gluten Free Options",4 of 5 bubbles,87 reviews,Stopped in yesterday for Breakfast. When in Je...
3061,Porto Leggero,Harborside Financial Center - Plaza 5,"Jersey City, NJ 07311","Italian, Vegetarian Friendly, Vegan Options",4.5 of 5 bubbles,183 reviews,First time for dinner. 2 couples. Delicious mu...

In [13]:
float(df["Reviews"][0].split(" ")[0])

4.5

In [26]:
r=[]
for x in df["Reviews"]:
    try:
        r.append(float(x.split(" ")[0]))
    except:
        r.append(0)
        
df["ratings"]=r

C:\Users\91981\Anaconda3\lib\site-packages\pandas\core\frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3062 entries, 0 to 3061
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            3062 non-null   object
 1   Street Address  3062 non-null   object
 2   Location        3062 non-null   object
 3   Type            3049 non-null   object
 4   Reviews         3062 non-null   object
 5   No of Reviews   3062 non-null   object
 6   Comments        2447 non-null   object
 7   ratings         3062 non-null   float64
dtypes: float64(1), object(7)
memory usage: 191.5+ KB

In [42]:
r=[]
for x in df["No of Reviews"]:
    try:
        r.append(int(x.split(" ")[0]))
    except:
        r.append(237)   #237 is avg no of reviews
df["No of User Ratings"]=r
df

C:\Users\91981\Anaconda3\lib\site-packages\pandas\core\frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

,Name,Street Address,Location,Type,Reviews,No of Reviews,Comments,ratings,No of User Ratings
0,Betty Lou's Seafood and Grill,318 Columbus Ave,"San Francisco, CA 94133-3908","Seafood, Vegetarian Friendly, Vegan Options",4.5 of 5 bubbles,243 reviews,NaN,4.5,243
1,Coach House Diner,55 State Rt 4,"Hackensack, NJ 07601-6337","Diner, American, Vegetarian Friendly",4 of 5 bubbles,84 reviews,"Both times we were there very late, after 11 P...",4.0,84
2,Table Talk Diner,2521 South Rd Ste C,"Poughkeepsie, NY 12601-5476","American, Diner, Vegetarian Friendly",4 of 5 bubbles,256 reviews,Waitress was very friendly but a little pricey...,4.0,256
3,Sixty Vines,3701 Dallas Pkwy,"Plano, TX 75093-7777","American, Wine Bar, Vegetarian Friendly",4.5 of 5 bubbles,235 reviews,Not sure why I went there for the second time....,4.5,235
4,The Clam Bar,3914 Brewerton Rd,"Syracuse, NY 13212","American, Bar, Seafood",4 of 5 bubbles,285 reviews,Doesn't look like much from the outside but wa...,4.0,285
...,...,...,...,...,...,...,...,...,...
3057,Indigo Kitchen & Ale House,2902 164th St SW,"Lynnwood, WA 98087-3201","American, Bar, Vegetarian Friendly",4.5 of 5 bubbles,198 reviews,We had to wait a few minutes to get it but it ...,4.5,198
3058,City Vineyard,233 West Street,"New York City, NY 10013","American, Bar, Seafood",4.5 of 5 bubbles,374 reviews,"Came here to see Andrea Gibson perform, we wer...",4.5,374
3059,BRIO Tuscan Grille,3710 US Highway 9,"Freehold, NJ 07728-4801","Steakhouse, Italian, Bar",4 of 5 bubbles,211 reviews,We come to Brio once a month. They are good fo...,4.0,211
3060,Maywood Pancake house,92 W Pleasant Ave,"Maywood, NJ 07607-1336","American, Vegan Options, Gluten Free Options",4 of 5 bubbles,87 reviews,Stopped in yesterday for Breakfast. When in Je...,4.0,87
3061,Porto Leggero,Harborside Financial Center - Plaza 5,"Jersey City, NJ 07311","Italian, Vegetarian Friendly, Vegan Options",4.5 of 5 bubbles,183 reviews,First time for dinner. 2 couples. Delicious mu...,4.5,183

In [44]:
df2=df.drop(['Reviews','No of Reviews'],axis=1)
df2

,Name,Street Address,Location,Type,Comments,ratings,No of User Ratings
0,Betty Lou's Seafood and Grill,318 Columbus Ave,"San Francisco, CA 94133-3908","Seafood, Vegetarian Friendly, Vegan Options",NaN,4.5,243
1,Coach House Diner,55 State Rt 4,"Hackensack, NJ 07601-6337","Diner, American, Vegetarian Friendly","Both times we were there very late, after 11 P...",4.0,84
2,Table Talk Diner,2521 South Rd Ste C,"Poughkeepsie, NY 12601-5476","American, Diner, Vegetarian Friendly",Waitress was very friendly but a little pricey...,4.0,256
3,Sixty Vines,3701 Dallas Pkwy,"Plano, TX 75093-7777","American, Wine Bar, Vegetarian Friendly",Not sure why I went there for the second time....,4.5,235
4,The Clam Bar,3914 Brewerton Rd,"Syracuse, NY 13212","American, Bar, Seafood",Doesn't look like much from the outside but wa...,4.0,285
...,...,...,...,...,...,...,...
3057,Indigo Kitchen & Ale House,2902 164th St SW,"Lynnwood, WA 98087-3201","American, Bar, Vegetarian Friendly",We had to wait a few minutes to get it but it ...,4.5,198
3058,City Vineyard,233 West Street,"New York City, NY 10013","American, Bar, Seafood","Came here to see Andrea Gibson perform, we wer...",4.5,374
3059,BRIO Tuscan Grille,3710 US Highway 9,"Freehold, NJ 07728-4801","Steakhouse, Italian, Bar",We come to Brio once a month. They are good fo...,4.0,211
3060,Maywood Pancake house,92 W Pleasant Ave,"Maywood, NJ 07607-1336","American, Vegan Options, Gluten Free Options",Stopped in yesterday for Breakfast. When in Je...,4.0,87
3061,Porto Leggero,Harborside Financial Center - Plaza 5,"Jersey City, NJ 07311","Italian, Vegetarian Friendly, Vegan Options",First time for dinner. 2 couples. Delicious mu...,4.5,183

In [45]:
df2.describe()

           ratings  No of User Ratings
count  3062.000000          3062.00000
mean      4.329197           237.74853
std       0.290978           196.06216
min       0.000000             1.00000
25%       4.000000            95.00000
50%       4.500000           194.00000
75%       4.500000           306.00000
max       5.000000           997.00000

In [56]:
df2[df2["ratings"]==0]

,Name,Street Address,Location,Type,Comments,ratings,No of User Ratings
1744,Wavershak's Deli,1800 Route 9,"Toms River, NJ 08755-1284",NaN,No Comments,0.0,237
2866,Wavershak's Deli,1800 Route 9,"Toms River, NJ 08755-1284",NaN,No Comments,0.0,237

In [59]:
len(df2["Name"].unique())

2641

In [68]:
df2=df2.drop_duplicates()

In [69]:
df2

,Name,Street Address,Location,Type,Comments,ratings,No of User Ratings
0,Betty Lou's Seafood and Grill,318 Columbus Ave,"San Francisco, CA 94133-3908","Seafood, Vegetarian Friendly, Vegan Options",NaN,4.5,243
1,Coach House Diner,55 State Rt 4,"Hackensack, NJ 07601-6337","Diner, American, Vegetarian Friendly","Both times we were there very late, after 11 P...",4.0,84
2,Table Talk Diner,2521 South Rd Ste C,"Poughkeepsie, NY 12601-5476","American, Diner, Vegetarian Friendly",Waitress was very friendly but a little pricey...,4.0,256
3,Sixty Vines,3701 Dallas Pkwy,"Plano, TX 75093-7777","American, Wine Bar, Vegetarian Friendly",Not sure why I went there for the second time....,4.5,235
4,The Clam Bar,3914 Brewerton Rd,"Syracuse, NY 13212","American, Bar, Seafood",Doesn't look like much from the outside but wa...,4.0,285
...,...,...,...,...,...,...,...
3055,Grazie,26 E 84th St,"New York City, NY 10028-0426","Italian, Vegetarian Friendly, Vegan Options",I went there with some friends and their baby ...,4.5,376
3057,Indigo Kitchen & Ale House,2902 164th St SW,"Lynnwood, WA 98087-3201","American, Bar, Vegetarian Friendly",We had to wait a few minutes to get it but it ...,4.5,198
3059,BRIO Tuscan Grille,3710 US Highway 9,"Freehold, NJ 07728-4801","Steakhouse, Italian, Bar",We come to Brio once a month. They are good fo...,4.0,211
3060,Maywood Pancake house,92 W Pleasant Ave,"Maywood, NJ 07607-1336","American, Vegan Options, Gluten Free Options",Stopped in yesterday for Breakfast. When in Je...,4.0,87
3061,Porto Leggero,Harborside Financial Center - Plaza 5,"Jersey City, NJ 07311","Italian, Vegetarian Friendly, Vegan Options",First time for dinner. 2 couples. Delicious mu...,4.5,183

In [ ]:
content_df = data[['Product ID', 'Product Name', 'Brand', 
                   'Category', 'Color', 'Size']]
content_df['Content'] = content_df.apply(lambda row: ' '.join(row.dropna().astype(str)), axis=1)

# Use TF-IDF vectorizer to convert content into a matrix of TF-IDF features
tfidf_vectorizer = TfidfVectorizer()
content_matrix = tfidf_vectorizer.fit_transform(content_df['Content'])

content_similarity = linear_kernel(content_matrix, content_matrix)

reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(data[['User ID', 
                                  'Product ID', 
                                  'Rating']], reader)

def get_content_based_recommendations(product_id, top_n):
    index = content_df[content_df['Product ID'] == product_id].index[0]
    similarity_scores = content_similarity[index]
    similar_indices = similarity_scores.argsort()[::-1][1:top_n + 1]
    recommendations = content_df.loc[similar_indices, 'Product ID'].values
    return recommendations

In [73]:
content_df = df2[['Name', 'Street Address', 'Location', 'Type', 'Comments']]
content_df['Content'] = content_df.apply(lambda row: ' '.join(row.dropna().astype(str)), axis=1)

content_df

C:\Users\91981\Anaconda3\lib\site-packages\pandas\core\frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

,Name,Street Address,Location,Type,Comments,Content
0,Betty Lou's Seafood and Grill,318 Columbus Ave,"San Francisco, CA 94133-3908","Seafood, Vegetarian Friendly, Vegan Options",NaN,Betty Lou's Seafood and Grill 318 Columbus Ave...
1,Coach House Diner,55 State Rt 4,"Hackensack, NJ 07601-6337","Diner, American, Vegetarian Friendly","Both times we were there very late, after 11 P...","Coach House Diner 55 State Rt 4 Hackensack, NJ..."
2,Table Talk Diner,2521 South Rd Ste C,"Poughkeepsie, NY 12601-5476","American, Diner, Vegetarian Friendly",Waitress was very friendly but a little pricey...,Table Talk Diner 2521 South Rd Ste C Poughkeep...
3,Sixty Vines,3701 Dallas Pkwy,"Plano, TX 75093-7777","American, Wine Bar, Vegetarian Friendly",Not sure why I went there for the second time....,"Sixty Vines 3701 Dallas Pkwy Plano, TX 75093-7..."
4,The Clam Bar,3914 Brewerton Rd,"Syracuse, NY 13212","American, Bar, Seafood",Doesn't look like much from the outside but wa...,"The Clam Bar 3914 Brewerton Rd Syracuse, NY 13..."
...,...,...,...,...,...,...
3055,Grazie,26 E 84th St,"New York City, NY 10028-0426","Italian, Vegetarian Friendly, Vegan Options",I went there with some friends and their baby ...,"Grazie 26 E 84th St New York City, NY 10028-04..."
3057,Indigo Kitchen & Ale House,2902 164th St SW,"Lynnwood, WA 98087-3201","American, Bar, Vegetarian Friendly",We had to wait a few minutes to get it but it ...,Indigo Kitchen & Ale House 2902 164th St SW Ly...
3059,BRIO Tuscan Grille,3710 US Highway 9,"Freehold, NJ 07728-4801","Steakhouse, Italian, Bar",We come to Brio once a month. They are good fo...,"BRIO Tuscan Grille 3710 US Highway 9 Freehold,..."
3060,Maywood Pancake house,92 W Pleasant Ave,"Maywood, NJ 07607-1336","American, Vegan Options, Gluten Free Options",Stopped in yesterday for Breakfast. When in Je...,Maywood Pancake house 92 W Pleasant Ave Maywoo...
3061,Porto Leggero,Harborside Financial Center - Plaza 5,"Jersey City, NJ 07311","Italian, Vegetarian Friendly, Vegan Options",First time for dinner. 2 couples. Delicious mu...,Porto Leggero Harborside Financial Center - Pl...

In [83]:
tfidf_vectorizer = TfidfVectorizer()
content_matrix = tfidf_vectorizer.fit_transform(df['Type'].apply(lambda x: np.str_(x)))

content_similarity = linear_kernel(content_matrix, content_matrix)

def get_content_based_recommendations(product_id, top_n):
    index = df[df['Name'] == product_id].index[0]
    similarity_scores = content_similarity[index]
    similar_indices = similarity_scores.argsort()[::-1][1:top_n + 1]
    recommendations = df.loc[similar_indices, 'Name'].values
    return recommendations

In [79]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [84]:
get_content_based_recommendations("Grazie", 5)

array(['Corso 98', 'Osteria 166', "Paolo's Italian Restaurant",
       'Biba Restaurant', "Trattoria L'incontro"], dtype=object)

In [89]:
df[df['Name']=="Grazie"]

,Name,Street Address,Location,Type,Reviews,No of Reviews,Comments
3055,Grazie,26 E 84th St,"New York City, NY 10028-0426","Italian, Vegetarian Friendly, Vegan Options",4.5 of 5 bubbles,376 reviews,I went there with some friends and their baby ...

In [91]:
l=['Corso 98', 'Osteria 166', "Paolo's Italian Restaurant",
       'Biba Restaurant', "Trattoria L'incontro"]

for i in l:
    print(df[df['Name']==i][["Name","Type"]])
    print()

          Name                                          Type
1034  Corso 98   Italian, Vegetarian Friendly, Vegan Options

             Name                                          Type
1049  Osteria 166   Italian, Vegetarian Friendly, Vegan Options

                            Name                                          Type
1066  Paolo's Italian Restaurant   Italian, Vegetarian Friendly, Vegan Options

                 Name                                          Type
2945  Biba Restaurant   Italian, Vegetarian Friendly, Vegan Options

                      Name                                          Type
1084  Trattoria L'incontro   Italian, Vegetarian Friendly, Vegan Options
1296  Trattoria L'incontro   Italian, Vegetarian Friendly, Vegan Options
1671  Trattoria L'incontro   Italian, Vegetarian Friendly, Vegan Options
2777  Trattoria L'incontro   Italian, Vegetarian Friendly, Vegan Options